# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Об авторе')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_original', models.CharField(max_length=255, verbose_name='Оригинальное название')),
                ('year_published', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN')),
                ('cover_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Твердая обложка'), (1, 'Мягкая обложка')], null=True, verbose_name='Тип обложки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.Author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Об издателе')),
            ],
            options={
                'verbose_name': 'издатель',
                'verbose_name_plural': 'издатели',
            },
        ),
        migrations.CreateModel(
            name='UserBookRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_bookmarks', models.BooleanField(default=False, verbose_name='В закладках')),
                ('in_wishlist', models.BooleanField(default=False, verbose_name='В списке желаний')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Так себе'), (4, 'Хорошо'), (5, 'Отлично')], null=True, verbose_name='Рейтинг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbookrelations', to='catalog.Book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbookrelations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='catalog.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.Publisher', verbose_name='Издательство'),
        ),
        migrations.AlterUniqueTogether(
            name='userbookrelation',
            unique_together=set([('book', 'user')]),
        ),
    ]
