# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='catalog.Category', verbose_name='Категории'),
        ),
    ]
