# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171211_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена без учета скидки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Итоговая цена'),
        ),
    ]
