# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Полная скидка в процентах'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='category',
            name='book_average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Средняя цена книги в категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='book_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество книг в категории'),
        ),
    ]
